name:                InHs
version:             0.1.0.0
github:              "ayush268/InHs"
license:             MIT
author:              "Ayush Bansal"
maintainer:          "ayushb268@gmail.com"
copyright:           "2019 Ayush Bansal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ayush268/InHs#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  InHs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - InHs

tests:
  InHs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - InHs
